# Generated 2018-11-05T17:16:39.609Z by Yipee editor
# Application: yipee

apiVersion: v1
kind: Service
metadata:
  name: yipee-backend
spec:
  selector:
    yipee.io/yipee-backend: generated
  ports:
  - port: 5000
    targetPort: 5000
    name: yipee-backend-5000
    protocol: TCP
    nodePort: 32005
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: yipee-ui
spec:
  selector:
    yipee.io/yipee-ui: generated
  ports:
  - port: 8080
    targetPort: 80
    name: yipee-ui-8080
    protocol: TCP
    nodePort: 32080
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yipee-ui
  annotations:
    yipee.generatedAt: '2018-11-05T17:16:39.573Z'
spec:
  selector:
    matchLabels:
      name: yipee
      component: yipee-ui
      yipee.io/yipee-ui: generated
  rollbackTo:
    revision: 0
  template:
    spec:
      imagePullSecrets: []
      containers:
      - name: yipee-ui
        image: yipeeio/yipee-ui:1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
    metadata:
      labels:
        name: yipee
        component: yipee-ui
        yipee.io/yipee-ui: generated
  strategy:
    type: RollingUpdate
    rollingUpdate: {}
  replicas: 1

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yipee-backend
  annotations:
    yipee.generatedAt: '2018-11-05T17:16:39.573Z'
spec:
  selector:
    matchLabels:
      name: yipee
      component: yipee-backend
      yipee.io/yipee-backend: generated
  rollbackTo:
    revision: 0
  template:
    spec:
      imagePullSecrets: []
      containers:
      - name: yipee-api
        image: yipeeio/yipee-api:1.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
      - name: yipee-converter
        image: yipeeio/yipee-converter:1.2
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
    metadata:
      labels:
        name: yipee
        component: yipee-backend
        yipee.io/yipee-backend: generated
  strategy:
    type: RollingUpdate
    rollingUpdate: {}
  replicas: 1
