# Generated 2019-01-21T23:46:55.772Z by Yipee editor
# Application: live

apiVersion: v1
kind: ServiceAccount
metadata:
  name: yipee-service-account

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: models.yipee.io
spec:
  group: yipee.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: models
    singular: model
    kind: YipeeModel
    shortNames:
    - ym

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yipee-cluster-actor
  labels:
    aggregate-to-admin: 'true'
    aggregate-to-edit: 'true'
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: yipee-crd-editor
  labels:
    aggregate-to-admin: 'true'
    aggregate-to-edit: 'true'
rules:
- apiGroups:
  - yipee.io
  resources:
  - models
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: yipee-crd-edit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yipee-crd-editor
subjects:
- kind: ServiceAccount
  name: yipee-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: yipee-cluster-actions
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yipee-cluster-actor
subjects:
- kind: ServiceAccount
  name: yipee-service-account
  namespace: default

---
apiVersion: v1
kind: Service
metadata:
  name: yipee-backend
  labels:
    yipee.io/yipee-backend: generated
  annotations:
    yipee.generatedAt: '2019-01-21T23:46:55.772Z'
spec:
  selector:
    yipee.io/yipee-backend: generated
  ports:
  - port: 5000
    targetPort: 5000
    name: backend-5000
    protocol: TCP
    nodePort: 32005
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: yipee-ui
  labels:
    yipee.io/yipee-ui: generated
  annotations:
    yipee.generatedAt: '2019-01-21T23:46:55.772Z'
spec:
  selector:
    yipee.io/yipee-ui: generated
  ports:
  - port: 8080
    targetPort: 80
    name: yipee-ui-8080
    protocol: TCP
    nodePort: 32080
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yipee-ui
  annotations:
    yipee.generatedAt: '2019-01-21T23:46:55.772Z'
spec:
  selector:
    matchLabels:
      name: yipee
      component: yipee-ui
      yipee.io/yipee-ui: generated
  template:
    spec:
      imagePullSecrets: []
      containers:
      - name: yipee-ui
        image: yipeeio/ui:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
    metadata:
      labels:
        name: yipee
        component: yipee-ui
        yipee.io/yipee-ui: generated
  strategy:
    type: RollingUpdate
    rollingUpdate: {}
  replicas: 1
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: yipee-layout-data
data:
  636f6e7461696e65722179697065652d636f6e766572746572: '33373521313235'
  636f6e7461696e65722179697065652d617069: '32353021313235'
  636f6e7461696e65722179697065652d7569: '32353021333030'
  636f6e7461696e65722d67726f75702179697065652d7569: '32323521323735'
  636f6e7461696e65722d67726f75702179697065652d6261636b656e64: '32323521313030'
  6b38732d736572766963652179697065652d7569: '31303021323735'
  6b38732d73657276696365216261636b656e64: '31303021313030'

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yipee-backend
  annotations:
    yipee.generatedAt: '2019-01-21T23:46:55.772Z'
spec:
  selector:
    matchLabels:
      name: yipee
      component: yipee-backend
      yipee.io/yipee-backend: generated
  template:
    spec:
      imagePullSecrets: []
      containers:
      - name: yipee-api
        env:
          - name: YIPEE_INSTALL_TYPE
            value: 'cluster'
        image: yipeeio/api:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
      - name: yipee-converter
        image: yipeeio/converter:2.0
        imagePullPolicy: Always
      restartPolicy: Always
      serviceAccountName: yipee-service-account
    metadata:
      labels:
        name: yipee
        component: yipee-backend
        yipee.io/yipee-backend: generated
  strategy:
    type: RollingUpdate
    rollingUpdate: {}
  replicas: 1
